### PR TITLE
🩹🚇 Adapt to changed outputs in pyglotaran-examples GHA

### PR DESCRIPTION
**Pull request by s-weigand**
Same as #273 but for staging_support

> This change fixes the [failing CI](https://github.com/glotaran/pyglotaran-extras/actions/runs/9629135960) due to changes in the outputs in the pyglotaran-examples github action.

### Change summary

- [🩹🚇 Adapt to changed outputs in pyglotaran-examples GHA](https://github.com/glotaran/pyglotaran-extras/commit/a2c6a90a34a54280dc77a282920fa0bb9fc92699)

### Checklist

- [x] ✔️ Passing the tests (mandatory for all PR's)

### CODE REVIEW

**Review by jsnel — COMMENTED** [review]
Pre-commit is failing.

**Comment by s-weigand** [comment]
I tried to fix tests as good as possible but staging is in a too bad state
- A-Marix in results doesn't have megacomplex post fix (🐛bug🐛)
- Result loading is not implemented (✨missing feature✨)

**Review by jsnel — APPROVED** [review]
OK

**Review by jsnel — APPROVED** [review]
Fixes some issues we're currently having. 👍 

The observed failures of unit tests are due to removal of that functionality from staging, not due to issues on the -extras side.

**Pull request merged**
